"""
Django settings for projet project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0*=fn_*9$vvbb=9u)uyzo%*0u38%c)e#gy#x5_l9zj2bo6g*a5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['Nouhailatl01.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DHT',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / "static" ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== CONFIGURATION EMAIL =====
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nouhaila.touil.23@ump.ac.ma'
EMAIL_HOST_PASSWORD = 'udue guih rlib wkgr'
DEFAULT_FROM_EMAIL = 'nouhaila.touil.23@ump.ac.ma'

# Email destinataire pour les alertes incidents
ALERT_EMAIL = 'nouhaila.touil.23@ump.ac.ma'
# ===== CONFIGURATION MQTT =====
MQTT_BROKER_ADDRESS = 'localhost'  # Adresse du broker MQTT
MQTT_BROKER_PORT = 1883  # Port MQTT (1883 par défaut, 8883 pour TLS)
MQTT_CLIENT_ID = 'django-dht11-client'  # ID unique du client
MQTT_USERNAME = None  # Nom d'utilisateur (None si non utilisé)
MQTT_PASSWORD = None  # Mot de passe (None si non utilisé)

# Topics MQTT
MQTT_TOPIC_SENSOR_DATA = 'dht11/sensor/data'  # Topic pour les données des capteurs
MQTT_TOPIC_INCIDENTS = 'dht11/incidents'  # Topic pour les incidents
MQTT_TOPIC_ALERTS = 'dht11/alerts'  # Topic pour les alertes
MQTT_TOPIC_STATUS = 'dht11/status'  # Topic pour le statut du service

# Seuils d'alerte (optionnel)
MQTT_TEMP_MIN = 5  # Température minimale
MQTT_TEMP_MAX = 35  # Température maximale
MQTT_HUM_MIN = 20  # Humidité minimale
MQTT_HUM_MAX = 80  # Humidité maximale