# Generated by Django 5.2.7 on 2026-01-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_product_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='operateur',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='operateur',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
