# Generated by Django 4.2.27 on 2026-01-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_incident_escalation_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='current_escalation_level',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='escalated_to_op2_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='escalated_to_op3_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='escalation_counter',
        ),
    ]
