# Generated by Django 5.2.7 on 2026-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_remove_incident_current_escalation_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-start_at']},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='max_hum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='min_hum',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='min_temp',
            field=models.FloatField(default=999),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('resolved', 'Résolu'), ('archived', 'Archivé')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op1_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op2_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op3_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
